export const RESTAURANT_INFO = {
  name: "مطعم نيو بورسعيد",
  nameEn: "New Port Said Restaurant",
  tagline: "أكل بشوات • طعم أصيل يُشوى بشغف",
  phones: ["01007375151", "01100130080", "01008329497"],
  address: "سوهاج الجديدة - مول ريتاج 1",
  whatsapp: "201100130080",
};

export const MENU_DATA = [
  {
    id: "grills",
    title: "المشويات",
    icon: "Flame",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD36-TZoKJowpy9x82axM8Fqne6mo0run_D4kmZZWiOog84SRZvpqx0X_JSwrVZaPVUpK_7CKz_4uMoJ918upJkL_a_s0tKrN_dUj5YWth2sPMOW1FrdoCxVzaTM6Lr4QddskZnje09rQ77ctdFVTSdZUdtUNcZzHE6Qb7wObHh0rO__bVgDfErd9VvE5qvglHgo09OPZNbyzUV8SfY2_v9gcjx8jQ_APUJzmvYcvKzzkgY6SiGJp_6xg",
    description: "أفخم أصناف الكباب، الكفتة، الريش والنيفة المشوية على الفحم الطبيعي بتتبيلة نيو بورسعيد السرية.",
    items: [
      { id: "g-1", name: "كباب", price: 980, badge: "مميز" },
      { id: "g-2", name: "ريش", price: 1020, badge: "اختيار الشيف" },
      { id: "g-3", name: "طرب", price: 900 },
      { id: "g-4", name: "نيفة", price: 980 },
      { id: "g-5", name: "كفتة", price: 800, badge: "الأكثر طلباً" },
      { id: "g-6", name: "مشكل", price: 900 },
      { id: "g-7", name: "فرخة فحم", price: 320 },
      { id: "g-8", name: "فرخة شيش", price: 340 },
      { id: "g-9", name: "فرخة شواية", price: 320 },
      { id: "g-10", name: "مخاصي", price: 720 },
      { id: "g-11", name: "كبدة", price: 880 },
      { id: "g-12", name: "سجق", price: 870 },
      { id: "g-13", name: "شيش طاووق", price: 720 },
      { id: "g-14", name: "ستيك مشوي", price: 980 },
      { id: "g-15", name: "طلب بقلاوة", price: 370 },
      { id: "g-16", name: "ميكس جريل", price: 360 },
      { id: "g-17", name: "حواوشي", price: 80, badge: "مقرمش" },
      {
        id: "g-18",
        name: "ميكس بورسعيد",
        price: 450,
        badge: "الأكثر مبيعاً",
        description: "سجق + كباب + كفتة + فراخ + أرز بسمتي + سلطات",
      },
      {
        id: "g-19",
        name: "طبق الملوك",
        price: 470,
        badge: "ملكي",
        description: "سجق + كفتة + ممبار + حمام + أرز بسمتي",
      },
    ],
  },
  {
    id: "trays",
    title: "الصواني",
    icon: "Crown",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCKW2CXhxJ6kBZux7iohwBiQ5scBIlgGsFUpz6XRKViel4VM3BWAREB4xoMNAXi6Rp7mPp-BqFQ7F2GpIJTEj4vM7IEdi3F9aPfMtBmwchTA6FIhv6vitZvim45xKHVGEEtBPatIRKi4dpblvpBVwPfI8GAC8gGlnZovUQK0rJfDz8BqoAtsu69znpgyncvkQd7CQS4ajaSCBZ1oPnIr5l9ka-osONM4GyvJlQPbg6Sc0s77x753ddmSA",
    description: "صواني العزومات واللمة الكبيرة تكفي العائلات وتجمع أشهى المشويات والمندي والمحاشي.",
    items: [
      {
        id: "t-1",
        name: "صينية العمدة",
        price: 880,
        badge: "عائلي",
        description: "أرز بسمتي + محاشي + 1/2 مندي فراخ + 1/4 لحم مندي + 1/4 كفتة + سلطات",
      },
      {
        id: "t-2",
        name: "صينية نيو بورسعيد",
        price: 3550,
        badge: "العزومة الكبرى",
        description: "1/2 شيش طاووق + 1/2 كباب + 1/2 كفتة + 1/2 نيفة + 1/2 مندي فراخ + 1/2 سجق + 2 لحم مندي + 3 حواوشي + محشي مشكل + ممبار + سمبوسك + 3 ملوخية + 8 شوربة لسان + سلطات",
      },
      {
        id: "t-3",
        name: "صينية 999",
        price: 1250,
        badge: "محبوبة الجماهير",
        description: "2 حمام + 1/2 كفتة + 1/2 فراخ شيش + محشي مشكل + ممبار + أرز بسمتي",
      },
      {
        id: "t-4",
        name: "صينية العيلة",
        price: 1850,
        badge: "لمة العيلة",
        description: "طاجن ورق عنب كوارع + 1/2 كفتة + 1/4 سجق + فرخة شواية + 2 حمام + 1/4 شيش طاووق + ورق عنب + كرنب + ممبار + أرز بسمتي",
      },
      {
        id: "t-5",
        name: "صينية الصحاب",
        price: 1020,
        badge: "للصحاب",
        description: "طاجن لحمة بالبصل + 1/4 كفتة + 1/2 فرخة شيش + محشي مشكل + أرز بسمتي",
      },
    ],
  },
  {
    id: "mandi",
    title: "المندي",
    icon: "Utensils",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBwKQXoMQ_bE95cgfOrLjTI0RbN78-dbPlRh_GPLa17GnFll8KO39DylTiRQnh62nasHBqFu9qM6sISprZNaEn9FGlrG7pb9XoIBtpIpjf1Zvzg2-qiJtigHREzee1YRq9OJeY5QmUtVUbkhV_1Mom8B3AmOYvMbHKmln_DK4qZgOEaX8cLj3ni-EhyDnsJ0vO6Ff_9xmOVboc-7Jc1p39MSFbAyx-GqwHHEA1_x3_bVw-mqZzJXk-4mA",
    description: "مندي مسوى على أصوله في براميل الحفرة بالأرز البسمتي المتبل والبهارات العطرية.",
    items: [
      { id: "m-1", name: "طلب لحمة مندي", price: 300, badge: "دايب" },
      { id: "m-2", name: "نصف فراخ مندي", price: 200 },
      { id: "m-3", name: "فرخة مندي", price: 400, badge: "مميز" },
    ],
  },
  {
    id: "oriental",
    title: "الشرقي",
    icon: "Sparkles",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBL6L0-dlINvY12z4Cg7jhDNBp-Exi581BuQAXZ-6_xbHyG_QkyxUA80gVwf6w8VneOlYSGB2YX4nSjJ64wTut6jOlzlC0vihYaoPqWUnmBKk9MtOwBf7TgAG-kC4QljHeVhF_jWJK-qhvZYadpc5Qf5Uk_ROJnt0U6_JD-dQyYA80PSXktgV3wuHPIok_aWI3ggJ3I2vGseq_qKTfw2mhL9vaXjlUjrjb-yYqplew082713qxwCCy4WA",
    description: "أصناف الفتات الشرقية، ورقة اللحمة والسجق، الحمام المحشي والبط والأكلات المصرية التراثية.",
    items: [
      { id: "o-1", name: "ورقة سجق", price: 270 },
      { id: "o-2", name: "ورقة لحمة جريل", price: 290, badge: "الأكثر طلباً" },
      { id: "o-3", name: "موزة ضاني فتة", price: 450, badge: "ملكي" },
      { id: "o-4", name: "موزة عجالي فتة", price: 370 },
      { id: "o-5", name: "بوفتيك", price: 265 },
      { id: "o-6", name: "حمام محشي فريك أو رز", price: 170, badge: "مخصوص" },
      { id: "o-7", name: "فرخة بلدي", price: 300 },
      { id: "o-8", name: "كبسة فراخ", price: 220 },
      { id: "o-9", name: "فراخ بانية", price: 170 },
      { id: "o-10", name: "كوارع فتة", price: 250, badge: "بالطشة" },
      { id: "o-11", name: "كبدة إسكندراني", price: 250 },
      { id: "o-12", name: "حمام طرب", price: 240 },
      { id: "o-13", name: "ضلعة ضاني", price: 450 },
      { id: "o-14", name: "هبرة ضاني", price: 450 },
      { id: "o-15", name: "نصف بطة + أرز + شوربة + ملوخية", price: "يومي", isDaily: true },
      { id: "o-16", name: "ريش مطبوخة", price: 450 },
      { id: "o-17", name: "موزة بالمحشي", price: 490, badge: "فاخر" },
      { id: "o-18", name: "موزة مطبوخة", price: 470 },
      { id: "o-19", name: "ريش بالمحشي", price: 470 },
      { id: "o-20", name: "طاسة نيفة بورق العنب", price: 490, badge: "اختيار الشيف" },
    ],
  },
  {
    id: "tajines",
    title: "الطواجن",
    icon: "Soup",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBL6L0-dlINvY12z4Cg7jhDNBp-Exi581BuQAXZ-6_xbHyG_QkyxUA80gVwf6w8VneOlYSGB2YX4nSjJ64wTut6jOlzlC0vihYaoPqWUnmBKk9MtOwBf7TgAG-kC4QljHeVhF_jWJK-qhvZYadpc5Qf5Uk_ROJnt0U6_JD-dQyYA80PSXktgV3wuHPIok_aWI3ggJ3I2vGseq_qKTfw2mhL9vaXjlUjrjb-yYqplew082713qxwCCy4WA",
    description: "طواجن الفخار المصرية الأصيلة المسواة في الفرن البلدي بالسمنة والتوابل الساخنة.",
    items: [
      { id: "taj-1", name: "طاجن لحمة بالبصل", price: 390, badge: "الأكثر طلباً" },
      { id: "taj-2", name: "طاجن خضار لحمة", price: 245 },
      { id: "taj-3", name: "طاجن بامية لحمة", price: 265 },
      { id: "taj-4", name: "طاجن حمام فريك ورق عنب", price: 265, badge: "مميز" },
      { id: "taj-5", name: "طاجن فريك لحمة", price: 245 },
      { id: "taj-6", name: "طاجن عكاوي بصل", price: 300, badge: "دايب" },
      { id: "taj-7", name: "طاجن عكاوي بامية", price: 350 },
      { id: "taj-8", name: "طاجن ورق عنب لحمة", price: 265 },
      { id: "taj-9", name: "طاجن كوارع ورق عنب", price: 265, badge: "اختيار الشيف" },
      { id: "taj-10", name: "طاجن لسان عصفور لحمة", price: 245 },
      { id: "taj-11", name: "طاجن سجق", price: 230 },
      { id: "taj-12", name: "طاجن حمام فريك", price: 230 },
      { id: "taj-13", name: "طاجن بامية سادة", price: 50 },
      { id: "taj-14", name: "طاجن داود باشا", price: 250 },
      { id: "taj-15", name: "طاجن ملوخية سادة", price: 50 },
      { id: "taj-16", name: "طاجن ملوخية كوارع", price: 130 },
      { id: "taj-17", name: "طاجن ملوخية لحمة", price: 230 },
      { id: "taj-18", name: "طاجن حمام كوارع", price: 315 },
      {
        id: "taj-19",
        name: "طاجن بورسعيد",
        price: 460,
        badge: "طاجن الموسم",
        description: "ضلوع + ورق عنب + بصل مكرمل",
      },
    ],
  },
  {
    id: "claypot",
    title: "الجرة",
    icon: "Flame",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD36-TZoKJowpy9x82axM8Fqne6mo0run_D4kmZZWiOog84SRZvpqx0X_JSwrVZaPVUpK_7CKz_4uMoJ918upJkL_a_s0tKrN_dUj5YWth2sPMOW1FrdoCxVzaTM6Lr4QddskZnje09rQ77ctdFVTSdZUdtUNcZzHE6Qb7wObHh0rO__bVgDfErd9VvE5qvglHgo09OPZNbyzUV8SfY2_v9gcjx8jQ_APUJzmvYcvKzzkgY6SiGJp_6xg",
    description: "جرار فخارية مغلقة مدفونة على الجمر حتى يذوب اللحم في نكهته العميقة.",
    items: [
      { id: "c-1", name: "جرة موزة", price: 460, badge: "دايبة" },
      { id: "c-2", name: "جرة أوزي", price: 460, badge: "مميز" },
      { id: "c-3", name: "جرة كوارع ورق عنب", price: 295 },
      { id: "c-4", name: "جرة عكاوي ورق عنب", price: 350 },
      { id: "c-5", name: "جرة حمام", price: 300 },
      { id: "c-6", name: "جرة لحمة", price: 450 },
    ],
  },
  {
    id: "mbakbaka",
    title: "المبكبكة",
    icon: "Soup",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCKW2CXhxJ6kBZux7iohwBiQ5scBIlgGsFUpz6XRKViel4VM3BWAREB4xoMNAXi6Rp7mPp-BqFQ7F2GpIJTEj4vM7IEdi3F9aPfMtBmwchTA6FIhv6vitZvim45xKHVGEEtBPatIRKi4dpblvpBVwPfI8GAC8gGlnZovUQK0rJfDz8BqoAtsu69znpgyncvkQd7CQS4ajaSCBZ1oPnIr5l9ka-osONM4GyvJlQPbg6Sc0s77x753ddmSA",
    description: "المبكبكة البدوية الأصيلة بالصلصة الغنية المتبلة والفلفل الحار واللحوم الطازجة.",
    items: [
      { id: "mb-1", name: "مبكبكة دجاج", price: 200 },
      { id: "mb-2", name: "مبكبكة سجق", price: 230, badge: "حارة ومبهرة" },
      { id: "mb-3", name: "مبكبكة موزة", price: 450, badge: "ملكي" },
      { id: "mb-4", name: "مبكبكة أوزي", price: 450 },
      { id: "mb-5", name: "مبكبكة لحمة عجالي", price: 385 },
    ],
  },
  {
    id: "chicken",
    title: "وجبات فراخ",
    icon: "Utensils",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuARQNCZLWoktE0AAD2ysgzsbx8jHZvCbRu3jTK0sNEmAnbDR32oeEcJpOFUZx0p3fp-4u4sRknmjv6LxeGwHD1zFKbkQIM-YUT0vJt6aUt1SJdaNbbcXYJdeLbceFIJk9vkvEYMls5WF-6TgBFfGZiYDzdOmyTX5Scg5ibPBuy_FpV7NHOM7z_Ay_gxzCyrb5GLjlgX1LVtcdahpY9TonlSpng6ThO4snBQfTonyVFAnuHYus0g4x8yVQ",
    description: "وجبات الدجاج المتكاملة المطهوة مع الخضار الطازج والأرز المصري.",
    items: [
      { id: "ch-1", name: "وجبة ورك بالخضار والأرز", price: 130 },
      { id: "ch-2", name: "وجبة صدر بالخضار والأرز", price: 140 },
      { id: "ch-3", name: "وجبة نصف فرخة بالخضار والأرز", price: 220, badge: "الأكثر طلباً" },
    ],
  },
  {
    id: "pasta_rice",
    title: "المكرونات والمعجنات",
    icon: "Utensils",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBL6L0-dlINvY12z4Cg7jhDNBp-Exi581BuQAXZ-6_xbHyG_QkyxUA80gVwf6w8VneOlYSGB2YX4nSjJ64wTut6jOlzlC0vihYaoPqWUnmBKk9MtOwBf7TgAG-kC4QljHeVhF_jWJK-qhvZYadpc5Qf5Uk_ROJnt0U6_JD-dQyYA80PSXktgV3wuHPIok_aWI3ggJ3I2vGseq_qKTfw2mhL9vaXjlUjrjb-yYqplew082713qxwCCy4WA",
    description: "صواني المكرونة البشاميل والنجرسكو والأرز بالخلطات والمكسرات.",
    items: [
      { id: "pr-1", name: "مكرونة بشاميل", price: 110, badge: "ساخنة" },
      { id: "pr-2", name: "مكرونة نجرسكو", price: 130 },
      { id: "pr-3", name: "مكرونة اسباجتي لحمة", price: 85 },
      { id: "pr-4", name: "مكرونة اسباجتي صلصة", price: 40 },
      { id: "pr-5", name: "مكرونة بنا صلصة", price: 40 },
      { id: "pr-6", name: "أرز شعرية", price: 30 },
      { id: "pr-7", name: "أرز أبيض", price: 25 },
      { id: "pr-8", name: "أرز بسمتي", price: 40 },
      { id: "pr-9", name: "أرز بالكبد والقوانص", price: 60 },
      {
        id: "pr-10",
        name: "مكرونة بورسعيد",
        price: 160,
        badge: "خاص بالمطعم",
        description: "مكرونة بنا + سجق + روز بيف مدخن + صوص نيو بورسعيد",
      },
    ],
  },
  {
    id: "appetizers",
    title: "فواتح شهية ومحاشي",
    icon: "Sparkles",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCKW2CXhxJ6kBZux7iohwBiQ5scBIlgGsFUpz6XRKViel4VM3BWAREB4xoMNAXi6Rp7mPp-BqFQ7F2GpIJTEj4vM7IEdi3F9aPfMtBmwchTA6FIhv6vitZvim45xKHVGEEtBPatIRKi4dpblvpBVwPfI8GAC8gGlnZovUQK0rJfDz8BqoAtsu69znpgyncvkQd7CQS4ajaSCBZ1oPnIr5l9ka-osONM4GyvJlQPbg6Sc0s77x753ddmSA",
    description: "أشهى أنواع السمبوسك المقرمشة، الممبار المحمر، والمحاشي المشكلة بالخلطة السرية.",
    items: [
      { id: "app-1", name: "سمبوسة لحمة", price: 65 },
      { id: "app-2", name: "سمبوسة فراخ", price: 55 },
      { id: "app-3", name: "سمبوسة جبنة", price: 50 },
      { id: "app-4", name: "محشي مشكل", price: 60 },
      { id: "app-5", name: "بطاطس بوم فريت", price: 25 },
      { id: "app-6", name: "محشي كرنب", price: 50 },
      { id: "app-7", name: "ورق عنب", price: 55 },
      { id: "app-8", name: "محشي ممبار", price: 60, badge: "مقرمش" },
      { id: "app-9", name: "ورق عنب + محاشي مشكلة", price: 110 },
      {
        id: "app-10",
        name: "ميكس محاشي بورسعيد",
        price: 280,
        badge: "طبق المشاركة",
        description: "ورق عنب + ممبار + كرنب + سمبوسك + محشي مشكل",
      },
    ],
  },
  {
    id: "soup",
    title: "الشوربة",
    icon: "Soup",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBL6L0-dlINvY12z4Cg7jhDNBp-Exi581BuQAXZ-6_xbHyG_QkyxUA80gVwf6w8VneOlYSGB2YX4nSjJ64wTut6jOlzlC0vihYaoPqWUnmBKk9MtOwBf7TgAG-kC4QljHeVhF_jWJK-qhvZYadpc5Qf5Uk_ROJnt0U6_JD-dQyYA80PSXktgV3wuHPIok_aWI3ggJ3I2vGseq_qKTfw2mhL9vaXjlUjrjb-yYqplew082713qxwCCy4WA",
    description: "شوربات ساخنة ومرقات بلدي بالمستكة والحبهان تفتتح بها عزومتك.",
    items: [
      { id: "sp-1", name: "شوربة لسان عصفور", price: 25 },
      { id: "sp-2", name: "شوربة كوارع", price: 95, badge: "طاقة ومغذية" },
      { id: "sp-3", name: "شوربة عدس", price: 25 },
      { id: "sp-4", name: "شوربة خضار", price: 30 },
      { id: "sp-5", name: "شوربة كريمة فراخ", price: 110 },
      { id: "sp-6", name: "شوربة كريمة ميكس", price: 120 },
      { id: "sp-7", name: "شوربة لسان عصفور لحمة", price: 100 },
      { id: "sp-8", name: "شوربة خضار لحمة", price: 120 },
      { id: "sp-9", name: "شوربة بهاريز", price: 50, badge: "مخصوص" },
    ],
  },
  {
    id: "salads",
    title: "السلطات والمخللات",
    icon: "Sparkles",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCKW2CXhxJ6kBZux7iohwBiQ5scBIlgGsFUpz6XRKViel4VM3BWAREB4xoMNAXi6Rp7mPp-BqFQ7F2GpIJTEj4vM7IEdi3F9aPfMtBmwchTA6FIhv6vitZvim45xKHVGEEtBPatIRKi4dpblvpBVwPfI8GAC8gGlnZovUQK0rJfDz8BqoAtsu69znpgyncvkQd7CQS4ajaSCBZ1oPnIr5l9ka-osONM4GyvJlQPbg6Sc0s77x753ddmSA",
    description: "سلطات طازجة يومية وطحينة سمسم فاخرة ومخللات بورسعيدية بالدقة والليمون.",
    items: [
      { id: "sal-1", name: "سلطة خضراء", price: 15 },
      { id: "sal-2", name: "سلطة طحينة", price: 20 },
      { id: "sal-3", name: "سلطة زبادي", price: 25 },
      { id: "sal-4", name: "سلطة حمص", price: 25 },
      { id: "sal-5", name: "سلطة بابا غنوج", price: 25 },
      { id: "sal-6", name: "سلطة بنجر بالفواكه", price: 40 },
      { id: "sal-7", name: "ثومية", price: 25 },
      { id: "sal-8", name: "كولسلو", price: 25 },
      { id: "sal-9", name: "مخلل مشكل", price: 20 },
      { id: "sal-10", name: "مخلل باذنجان", price: 15 },
      { id: "sal-11", name: "طماطم متبلة", price: 15 },
      { id: "sal-12", name: "ليمون مخلل", price: 15 },
      {
        id: "sal-13",
        name: "سلطة بورسعيد",
        price: 100,
        badge: "سلطة الشيف",
        description: "خس + شرائح فراخ + تفاح + صوص بورسعيد الخاص",
      },
    ],
  },
  {
    id: "fresh_drinks",
    title: "المشروبات الفريش والعصائر",
    icon: "Coffee",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCPugHcLuXd6NOGThwuxyZ4en5d40T01EQ72DcDXpEgddLjiudguVvuRhrVkDYkdEjqWwASqA04EcSJCT0JI1cUKWoWdc2V3JQehwhOgrt8XTIGYsRMsgTL9VEXhWW6LR79H_359o3MV0oU7JCvcjlzJkyyMl4ct_uj1TC7Oeobts8bg64d_pRIWP7X1zUdOU3PLQE44VBfnvXl30g8NDdFm6N9IZHNB2nlanek4bSKeI50iszGbqhe6A",
    description: "عصائر طبيعية فريش 100% ومشروبات غازية منعشة ومثلجة.",
    items: [
      { id: "fd-1", name: "مياه", price: 10 },
      { id: "fd-2", name: "في كولا", price: 25 },
      { id: "fd-3", name: "بيبسي", price: 25 },
      { id: "fd-4", name: "بريل", price: 30 },
      { id: "fd-5", name: "بيبسي دايت", price: 30 },
      { id: "fd-6", name: "كيوي فريش", price: 60 },
      { id: "fd-7", name: "مانجو طبيعي", price: 50, badge: "منعش" },
      { id: "fd-8", name: "أفوكادو", price: 100, badge: "طاقة" },
      { id: "fd-9", name: "جوافة", price: 45 },
      { id: "fd-10", name: "برتقال فريش", price: 40 },
      { id: "fd-11", name: "ليمون نعناع", price: 40, badge: "الأكثر طلباً" },
      { id: "fd-12", name: "آيس كريم بولتين", price: 30 },
      { id: "fd-13", name: "موهيتو", price: 45 },
      { id: "fd-14", name: "زبادي مانجا", price: 55 },
      { id: "fd-15", name: "آيس كوفي", price: 50 },
      { id: "fd-16", name: "موز بلبن", price: 45 },
      { id: "fd-17", name: "فراولة", price: 45 },
      { id: "fd-18", name: "فروت سلاد", price: 70 },
      { id: "fd-19", name: "تفاح", price: 60 },
      { id: "fd-20", name: "كنتالوب", price: 40 },
    ],
  },
  {
    id: "hot_drinks",
    title: "المشروبات الساخنة",
    icon: "Coffee",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCPugHcLuXd6NOGThwuxyZ4en5d40T01EQ72DcDXpEgddLjiudguVvuRhrVkDYkdEjqWwASqA04EcSJCT0JI1cUKWoWdc2V3JQehwhOgrt8XTIGYsRMsgTL9VEXhWW6LR79H_359o3MV0oU7JCvcjlzJkyyMl4ct_uj1TC7Oeobts8bg64d_pRIWP7X1zUdOU3PLQE44VBfnvXl30g8NDdFm6N9IZHNB2nlanek4bSKeI50iszGbqhe6A",
    description: "شاي كرك، قهوة تركي مظبوطة ومشروبات دافئة بعد المشاوي.",
    items: [
      { id: "hd-1", name: "شاي", price: 20 },
      { id: "hd-2", name: "ينسون", price: 20 },
      { id: "hd-3", name: "قهوة تركي", price: 30, badge: "بوش" },
      { id: "hd-4", name: "شاي كرك", price: 30, badge: "بالهيل والزعفران" },
      { id: "hd-5", name: "هوت شوكليت", price: 40 },
      { id: "hd-6", name: "نسكافيه", price: 35 },
      { id: "hd-7", name: "إسبريسو", price: 40 },
    ],
  },
  {
    id: "desserts",
    title: "الحلويات",
    icon: "Heart",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBL6L0-dlINvY12z4Cg7jhDNBp-Exi581BuQAXZ-6_xbHyG_QkyxUA80gVwf6w8VneOlYSGB2YX4nSjJ64wTut6jOlzlC0vihYaoPqWUnmBKk9MtOwBf7TgAG-kC4QljHeVhF_jWJK-qhvZYadpc5Qf5Uk_ROJnt0U6_JD-dQyYA80PSXktgV3wuHPIok_aWI3ggJ3I2vGseq_qKTfw2mhL9vaXjlUjrjb-yYqplew082713qxwCCy4WA",
    description: "أطباق الحلوى المصرية اللذيذة والباردة لختام وجبة مثالية.",
    items: [
      { id: "des-1", name: "رز بلبن", price: 30, badge: "كريمي" },
      { id: "des-2", name: "جيلي", price: 25 },
      { id: "des-3", name: "كريم كراميل", price: 25, badge: "ناعم ولذيذ" },
    ],
  },
];
